### ISSUE TITLE
Mocha unit test failing when component imports Icon.vue

### ISSUE THREAD

**Issue by d1820** [Justineo/vue-awesome#65]
Trying to create some mocha unit tests, and cant seem to get past the vue-awesome import statements, its like they are not being sent through the vue-loader. but the site runs correctly.

If anyone has any insight, kinda stuck at this point..

Thanks

**error**
```
C:\Dev\UIKit\node_modules\vue-awesome\components\Icon.vue:1
(function (exports, require, module, __filename, __dirname) { <template>
                                                              ^

SyntaxError: Unexpected token <
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object._module2.default._extensions.(anonymous function) [as .js] (C:\Dev\UIKit\node_modules\mocha-webpack\lib\util\registerRequireHoo
k.js:140:62)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Dev\UIKit\.tmp\mocha-webpack\1508106917398\external "vue-awesome\components\Icon.vue":1:1)
    at __webpack_require__ (C:\Dev\UIKit\.tmp\mocha-webpack\1508106917398\webpack\bootstrap 7d63c07ca1058a0ed76a:19:1)
    at Object.<anonymous> (C:\Dev\UIKit\.tmp\mocha-webpack\1508106917398\bundle.js:818:90)
    at __webpack_require__ (C:\Dev\UIKit\.tmp\mocha-webpack\1508106917398\webpack\bootstrap 7d63c07ca1058a0ed76a:19:1)
    at Object.<anonymous> (C:\Dev\UIKit\.tmp\mocha-webpack\1508106917398\bundle.js:1724:100)
    at __webpack_require__ (C:\Dev\UIKit\.tmp\mocha-webpack\1508106917398\webpack\bootstrap 7d63c07ca1058a0ed76a:19:1)
    at Object.<anonymous> (C:\Dev\UIKit\.tmp\mocha-webpack\1508106917398\bundle.js:1432:114)
    at __webpack_require__ (C:\Dev\UIKit\.tmp\mocha-webpack\1508106917398\webpack\bootstrap 7d63c07ca1058a0ed76a:19:1)
    at run (C:\Dev\UIKit\node_modules\mocha-webpack\lib\entry.js:3:19)
    at Array.forEach (native)
    at Object.<anonymous> (C:\Dev\UIKit\node_modules\mocha-webpack\lib\entry.js:10:1)
    at Object.<anonymous> (C:\Dev\UIKit\.tmp\mocha-webpack\1508106917398\bundle.js:1389:30)
    at __webpack_require__ (C:\Dev\UIKit\.tmp\mocha-webpack\1508106917398\webpack\bootstrap 7d63c07ca1058a0ed76a:19:1)
    at C:\Dev\UIKit\.tmp\mocha-webpack\1508106917398\webpack\bootstrap 7d63c07ca1058a0ed76a:62:1
    at Object.<anonymous> (C:\Dev\UIKit\.tmp\mocha-webpack\1508106917398\bundle.js:66:10)
    at Module._compile (module.js:570:32)
    at Object._module2.default._extensions.(anonymous function) [as .js] (C:\Dev\UIKit\node_modules\mocha-webpack\lib\util\registerRequireHoo
k.js:147:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\Dev\UIKit\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Dev\UIKit\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (C:\Dev\UIKit\node_modules\mocha\lib\mocha.js:514:10)
    at C:\Dev\UIKit\node_modules\mocha-webpack\lib\runner\TestRunner.js:193:25
    at Compiler.<anonymous> (C:\Dev\UIKit\node_modules\mocha-webpack\lib\webpack\compiler\registerReadyCallback.js:26:7)
    at Compiler.applyPlugins (C:\Dev\UIKit\node_modules\tapable\lib\Tapable.js:61:14)
    at emitRecords.err (C:\Dev\UIKit\node_modules\webpack\lib\Compiler.js:268:11)
    at Compiler.emitRecords (C:\Dev\UIKit\node_modules\webpack\lib\Compiler.js:375:38)
    at emitAssets.err (C:\Dev\UIKit\node_modules\webpack\lib\Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (C:\Dev\UIKit\node_modules\webpack\lib\Compiler.js:368:12)
    at next (C:\Dev\UIKit\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (C:\Dev\UIKit\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (C:\Dev\UIKit\node_modules\tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit (C:\Dev\UIKit\node_modules\webpack\lib\Compiler.js:365:9)
    at require.forEach.err (C:\Dev\UIKit\node_modules\webpack\lib\Compiler.js:354:15)
    at C:\Dev\UIKit\node_modules\async\dist\async.js:421:16
    at iteratorCallback (C:\Dev\UIKit\node_modules\async\dist\async.js:998:13)
    at C:\Dev\UIKit\node_modules\async\dist\async.js:906:16
    at MemoryFileSystem.writeFile (C:\Dev\UIKit\node_modules\memory-fs\lib\MemoryFileSystem.js:328:9)
    at writeOut (C:\Dev\UIKit\node_modules\webpack\lib\Compiler.js:343:28)
    at require.forEach (C:\Dev\UIKit\node_modules\webpack\lib\Compiler.js:349:12)
    at C:\Dev\UIKit\node_modules\async\dist\async.js:3083:16
    at eachOfArrayLike (C:\Dev\UIKit\node_modules\async\dist\async.js:1003:9)
    at eachOf (C:\Dev\UIKit\node_modules\async\dist\async.js:1051:5)
    at Object.eachLimit (C:\Dev\UIKit\node_modules\async\dist\async.js:3145:5)
    at emitFiles (C:\Dev\UIKit\node_modules\webpack\lib\Compiler.js:319:21)
    at Immediate.<anonymous> (C:\Dev\UIKit\node_modules\memory-fs\lib\MemoryFileSystem.js:288:4)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)


npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! geniusavenue-uikit@1.0.0 test: `mocha-webpack --opts test/mocha.opts `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the -uikit@1.0.0 test script 'mocha-webpack --opts test/mocha.opts '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the geniusavenue-uikit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha-webpack --opts test/mocha.opts
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs geniusavenue-uikit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls geniusavenue-uikit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```
**Component**
```
import Icon from 'vue-awesome/components/Icon.vue';
import 'vue-awesome/icons/eye';
import 'vue-awesome/icons/eye-slash';

let Control = { }
```

**Component template**
```
<template>
<div class="ga-control-button-addon" v-if="!hideToggle" :class="[{'disabled': !hasContent}]" v-on:click.prevent="toggle">
            <icon :name="toggleIcon"></icon>
</div>
</template>
```

Unit test spec
```
import Vue from 'vue';
import * as sinon from 'sinon';
import {shallow} from 'avoriaz';
import {assert, expect} from 'chai';
import gatextbox from '@/components/uikit/component.vue';
import '@/components/uikit/component';

describe('TestComponent', () => {
    let wrapper;
    beforeEach(() => {
        const instance = Vue.extend();
        wrapper = shallow(gatextbox, {
            instance
        });
    });
//shortened to relavant code...
});
```

**webpack**
```
const nodeExternals = require('webpack-node-externals');
const isCoverage = process.env.NODE_ENV === 'coverage';
const path = require('path');

function resolve(dir) {
    return path.resolve(__dirname, dir);
}

module.exports = {
    devtool: 'source-map',
    output: {
        // use absolute paths in sourcemaps (important for debugging via IDE)
        devtoolModuleFilenameTemplate: '[absolute-resource-path]',
        devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]'
    },
    /*
      Use webpack-node-externals to prevent bundling anything referenced in node_modules.
      At runtime, these modules can be loaded by Node and therefore do not need to be bundled by Webpack. */
    externals: [
        nodeExternals()
    ],
    resolve: {
        extensions: ['.js', '.vue'],
        alias: {
            'vue$': 'vue/dist/vue.common.js',
            '@': resolve('src')
        }
    },
    module: {
        rules: [].concat(
            {
                test: /\.vue$/,
                loader: 'vue-loader',
                exclude: /node_modules(?![\\/]vue-awesome[\\/])/,
                options: {
                    loaders: {
                        js: 'babel-loader',
                        less: 'style-loader!css-loader?sourceMap=true!less-loader?sourceMap=true'
                    }

                }
            },
            {
                test: /\.js$/,
                loader: 'babel-loader',
                exclude: /node_modules/
            },
            isCoverage ? {
                test: /\.js|\.vue$/,
                use: {
                    loader: 'istanbul-instrumenter-loader',
                    options: {esModules: true, produceSourceMap: true}
                },
                enforce: 'post',
                exclude: /node_modules|\.spec\.js$/
            } : []

        )
    }
};

```

**Comment by Justineo** [comment]
I've updated the readme and maybe you can try this first: https://github.com/Justineo/vue-awesome#heads-up

The problem here is that the webpack config excluded `node_modules` while Vue-Awesome requires Babel if you directly import the source version.

**Comment by d1820** [comment]
The updated Readme set me on the correct path. My issue was from using the webpack-node-externals  plugin. in using that plugin you will need to whitelist vue-awesome

```
externals: [
        nodeExternals({whitelist: [/^vue-awesome/,/^lodash/]})
    ],
```

Doing that gets the webpack test compile working.

here is the full testing webpack i have successfully working now

```
const nodeExternals = require('webpack-node-externals');
const isCoverage = process.env.NODE_ENV === 'coverage';
const path = require('path');

function resolve(dir) {
    return path.resolve(__dirname, dir);
}

module.exports = {
    devtool: 'source-map',
    output: {
        // use absolute paths in sourcemaps (important for debugging via IDE)
        devtoolModuleFilenameTemplate: '[absolute-resource-path]',
        devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]'
    },
    /*
      Use webpack-node-externals to prevent bundling anything referenced in node_modules.
      At runtime, these modules can be loaded by Node and therefore do not need to be bundled by Webpack. */
    externals: [
        nodeExternals({whitelist: [/^vue-awesome/,/^lodash/]})
    ],
    resolve: {
        extensions: ['.js', '.vue'],
        alias: {
            'vue$': 'vue/dist/vue.common.js',
            '@': resolve('src')
        }
    },
    module: {
        rules: [].concat(
            {
                test: /\.vue$/,
                loader: 'vue-loader',
                exclude: /node_modules(?![\\/]vue-awesome[\\/])/,
                options: {
                    loaders: {
                        js: 'babel-loader',
                        less: 'style-loader!css-loader?sourceMap=true!less-loader?sourceMap=true'
                    }

                }
            },
            {
                test: /\.js$/,
                loader: 'babel-loader'
            },
            isCoverage ? {
                test: /\.js|\.vue$/,
                use: {
                    loader: 'istanbul-instrumenter-loader',
                    options: {esModules: true, produceSourceMap: true}
                },
                enforce: 'post',
                exclude: /node_modules|\.spec\.js$/
            } : []
        )
    }
};

```

@Justineo  Thanks for the help +1
