### ISSUE TITLE
correct use / import

### ISSUE THREAD

**Issue by mnooblet** [Justineo/vue-awesome#66]
I cloned the hackernews example app with SSRS and I'm trying to use this icons but something goes wrong

```
import 'vue-awesome/icons'
import Icon from 'vue-awesome/components/Icon.vue'

export default {
  components : {
    Icon
  },
```

thats how I try to import the icons

```
error during render : /
/home/examples/vue/hackernews/node_modules/vue-awesome/icons/index.js:1
(function (exports, require, module, __filename, __dirname) { import './500px'
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

```

**Comment by d1820** [comment]
Ive seen that to, as part of Issue #65

**Comment by Justineo** [comment]
Hi, you should exclude `vue-awesome` from the `exclude` field of the webpack config for `babel-loader` to solve this. See https://github.com/Justineo/vue-awesome#heads-up.

**Comment by mnooblet** [comment]
I tried both include and export settings, but I'm still getting the same error

thats my webpack.base.config

```
const path = require('path')
const webpack = require('webpack')
const vueConfig = require('./vue-loader.config')
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const FriendlyErrorsPlugin = require('friendly-errors-webpack-plugin')

const isProd = process.env.NODE_ENV === 'production'


module.exports = {
  devtool: isProd
    ? false
    : '#cheap-module-source-map',
  output: {
    path: path.resolve(__dirname, '../dist'),
    publicPath: '/dist/',
    filename: '[name].[chunkhash].js'
  },
  resolve: {
    alias: {
      'public': path.resolve(__dirname, '../public')
    }
  },
  module: {
    noParse: /es6-promise\.js$/, // avoid webpack shimming process
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        include: [path.resolve('node_modules/vue-awesome')]
      },
      {
        test: /\.(png|jpg|gif|svg)$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: '[name].[ext]?[hash]'
        }
      },
      {
        test: /\.css$/,
        use: isProd
          ? ExtractTextPlugin.extract({
              use: 'css-loader?minimize',
              fallback: 'vue-style-loader'
            })
          : ['vue-style-loader', 'css-loader']
      }
    ]
  },
  performance: {
    maxEntrypointSize: 300000,
    hints: isProd ? 'warning' : false
  },
  plugins: isProd
    ? [
        new webpack.optimize.UglifyJsPlugin({
          compress: { warnings: false }
        }),
        new webpack.optimize.ModuleConcatenationPlugin(),
        new ExtractTextPlugin({
          filename: 'common.[chunkhash].css'
        })
      ]
    : [
        new FriendlyErrorsPlugin()
      ]
}
```

I cloned this repo https://github.com/vuejs/vue-hackernews-2.0 and tried to get Icons working, can you have a look on how to setup webpack there?

**Comment by tatsujb** [comment]
I have a similar issue the guide doesn't. help me fix this. my page loads but 

```
webpack-internal:///2:572 [Vue warn]: Unknown custom element: <icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <LateralMenu> at src\components\lateralmenu\LateralMenu.vue
       <Main> at src\components\Main.vue
         <App> at src\App.vue
           <Root>
```

this happens and the icon doesn't show up.

**Comment by blocka** [comment]
@tatsujb what did you mean by making the import and export global? I'm also having this issue, starting from vue-hackernews, as well

**Comment by blocka** [comment]
This worked for me: https://github.com/Justineo/vue-awesome/issues/65#issuecomment-337116728

**Comment by Justineo** [comment]
For SSR you need to:

1. Make sure the component code goes through `babel-loader` by modifying the `exclude` option.
2. When using `webpack-node-externals`, whitelist `vue-awesome` to include it into the server bundle.

You can look into the example provided by @d1820 here: https://github.com/Justineo/vue-awesome/issues/65#issuecomment-337116728

**Comment by blocka** [comment]
Worth putting that in the readme

**Comment by Justineo** [comment]
@blocka Yep, I'm updating it right now.

**Comment by mnooblet** [comment]
thanks for looking into that again, for me the webpack-node-externals whitelist option was the thing that was missing, I didn't modify the exclude option ( using the hackernews example )

**Comment by dcrystalj** [comment]
I am using vue-cli. it is working in dev. but running vue jest i get
```
   ...widgets\node_modules\vue-awesome\icons\volume-up.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Icon from '../components/Icon.vue'
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import
```
