### ISSUE TITLE
Loading Icon.vue from ts-loader

### ISSUE THREAD

**Issue by d1820** [Justineo/vue-awesome#68]
I followed the previous bug/resolution of adding vue-awesome to the include path and receive the following error. I think it has something to do with TS-Loader, that seems to be the only difference

```
in ./~/ts-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-awesome/components/Icon.vue
Module build failed: Error: Could not find file: 'C:\Dev\Marketplace-Web-Consumer\Marketplace.Web.ServiceFabric\node_modules\vue-awesome\components\Icon.vue'.
    at getValidSourceFile (C:\Dev\GeniusAvenue\Marketplace-Web-Consumer\Marketplace.Web.ServiceFabric\node_modules\typescript\lib\typescript.js:86054:23)
    at Object.getEmitOutput (C:\Dev\Marketplace-Web-Consumer\Marketplace.Web.ServiceFabric\node_modules\typescript\lib\typescript.js:86415:30)
    at getEmit (C:\Dev\Marketplace-Web-Consumer\Marketplace.Web.ServiceFabric\node_modules\ts-loader\dist\index.js:143:43)
    at successLoader (C:\Dev\Marketplace-Web-Consumer\Marketplace.Web.ServiceFabric\node_modules\ts-loader\dist\index.js:42:11)
    at Object.loader (C:\Dev\Marketplace-Web-Consumer\Marketplace.Web.ServiceFabric\node_modules\ts-loader\dist\index.js:29:12)
 @ ./~/vue-awesome/components/Icon.vue 7:2-85
 @ ./~/ts-loader!./ClientApp/components/app/app.ts
 @ ./ClientApp/components/app/app.vue
 @ ./ClientApp/boot.ts
 @ multi event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot.ts
```

webpack
```
const path = require('path');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const bundleOutputDir = './wwwroot/dist';

module.exports = (env) => {
    const isDevBuild = !(env && env.prod);

    return [{
        context: __dirname,
        devtool: isDevBuild ? 'cheap-module-eval-source-map' : 'source-map',
        resolve: {
            extensions: ['.js', '.ts', '.vue', 'scss'],
            modules: [
                path.resolve(__dirname + '/ClientApp'),
                path.resolve(__dirname + '/node_modules')
            ]
        },
        entry: { 'main': './ClientApp/boot.ts' },
        module: {
            rules: [
                {
                    test: /\.vue$/,
                    include: [path.join(__dirname , 'ClientApp'), path.join(__dirname , 'node_modules/vue-awesome')],
                    loader: 'vue-loader',
                    exclude: /node_modules(?![\\/]vue-awesome[\\/])/,
                    options: {
                        loaders: {
                            js: 'ts-loader',
                            ts: 'ts-loader',
                            scss:
                            'style-loader!css-loader?sourceMap=true?sourceMap=true!sass-loader?outputStyle=expanded&sourceMap=true&sourceMapContents=true'
                        }

                    }
                },
                {
                    test: /\.ts$/,
                    exclude: /node_modules(?![\\/]vue-awesome[\\/])/,
                    include: [path.join(__dirname, 'ClientApp'), path.join(__dirname, 'node_modules/vue-awesome')],
                    use: 'ts-loader'
                },
                {
                    test: /\.scss$/,
                    use: isDevBuild
                        ? [
                            'style-loader', 'css-loader?sourceMap=true',
                            'sass-loader?outputStyle=expanded&sourceMap=true&sourceMapContents=true'
                        ]
                        : ExtractTextPlugin.extract({
                            fallbackLoader: 'style-loader',
                            use: 'css-loader?minimize!sass-loader'
                        })
                },
                {
                    test: /\.(png|jpg|jpeg|gif|svg)$/,
                    use: 'url-loader?limit=25000'
                }
            ]
        },
        output: {
            path: path.join(__dirname, bundleOutputDir),
            filename: '[name].js',
            publicPath: 'dist/'
        },
        plugins: [
            //            new CopyWebpackPlugin([
            //                { from: './node_modules/msal/out/msal.js', flatten: true }
            //            ]
            //            ),

            new webpack.DefinePlugin({
                'process.env': {
                    NODE_ENV: JSON.stringify(isDevBuild ? 'development' : 'production')
                }
            }),
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./wwwroot/dist/vendor-manifest.json')
            }),

        ].concat(isDevBuild ? [
            // Plugins that apply in development builds only
            new webpack.SourceMapDevToolPlugin({
                filename: '[file].map', // Remove this line if you prefer inline source maps
                moduleFilenameTemplate: path.relative(bundleOutputDir, '[resourcePath]') // Point sourcemap entries to the original file locations on disk
            })
        ] : [
                // Plugins that apply in production builds only
                new webpack.optimize.UglifyJsPlugin({ sourceMap: true }),
                new webpack.optimize.ModuleConcatenationPlugin(),
                new ExtractTextPlugin('site.css')
            ]),
        stats: {
            colors: true,
            hash: true,
            version: true,
            timings: true,
            assets: false,
            chunks: false,
            chunkModules: false,
            modules: true,
            children: false,
            cached: false,
            reasons: true,
            source: false,
            errorDetails: true,
            chunkOrigins: false
        }

    }];
};

Code
``
import Icon from 'vue-awesome/components/Icon.vue';
import 'vue-awesome/icons/eye';

components = [{Icon}]
``

Dependencies

```
 "dependencies": {
    "axios": "0.16.2",
    "bootstrap": "3.3.7",
    "bootstrap-vue": "1.0.0-beta.9",
    "es-cookie": "1.1.1",
    "event-source-polyfill": "0.0.9",
    "inversify": "4.3.0",
    "inversify-inject-decorators": "3.0.1",
    "lodash": "4.17.4",
    "reflect-metadata": "0.1.10",
    "vue": "2.4.4",
    "vue-awesome": "2.3.3",
    "vue-class-component": "5.0.2",
    "vue-property-decorator": "5.3.0",
    "vue-router": "2.7.0",
    "vue-template-compiler": "2.4.4",
    "vuex": "2.4.0",
    "vuex-router-sync": "2.1.1",
    "vuex-typescript": "0.1.0"
  },
    "devDependencies": {
        "@types/chai": "4.0.4",
        "@types/lodash": "4.14.76",
        "@types/mocha": "2.2.43",
        "@types/sinon": "2.3.5",
        "@types/webpack-env": "1.13.0",
        "aspnet-prerendering": "3.0.1",
        "aspnet-webpack": "2.0.1",
        "avoriaz": "4.2.0",
        "awesome-typescript-loader": "3.2.3",
        "bind-decorator": "1.0.11",
        "chai": "4.1.2",
        "copy-webpack-plugin": "4.1.0",
        "cross-env": "5.0.5",
        "css-loader": "0.28.7",
        "extract-text-webpack-plugin": "3.0.0",
        "file-loader": "0.11.2",
        "git-commit": "0.0.3",
        "istanbul-instrumenter-loader": "3.0.0",
        "jsdom": "11.2.0",
        "jsdom-global": "3.0.2",
        "json-loader": "0.5.7",
        "lodash-ts-imports-loader": "1.1.2",
        "mocha": "3.5.3",
        "mocha-webpack": "1.0.0-rc.1",
        "node-inspector": "1.1.1",
        "node-sass": "4.5.3",
        "nyc": "11.2.1",
        "pre-commit": "^1.2.2",
        "sass-loader": "6.0.6",
        "sinon": "3.3.0",
        "source-map-support": "https://registry.npmjs.org/source-map-support/-/source-map-support-0.4.15.tgz",
        "style-loader": "0.18.2",
        "ts-loader": "3.0.5",
        "ts-node": "3.3.0",
        "tslint": "5.7.0",
        "typescript": "2.5.2",
        "url-loader": "0.5.9",
        "vue-cli": "2.8.2",
        "vue-inject": "1.0.1",
        "vue-loader": "13.0.5",
        "webpack": "3.6.0",
        "webpack-hot-middleware": "2.19.1",
        "webpack-node-externals": "1.6.0"
    }
```

Anyone used this with Vue and Typescript? 
```

**Comment by d1820** [comment]
This webpack configuration seems to resolve the issue. Im not really sure why i need to double run the ts-loader.. but in doing so it resolves the ability to compile the Icon.vue

```
 {
                    test: /\.vue$/,
                    include: [path.join(__dirname , 'ClientApp')],
                    loader: 'vue-loader',
                    exclude: /node_modules/,
                    options: {
                        loaders: {
                            js: 'ts-loader',
                            ts: 'ts-loader',
                            scss:
                            'style-loader!css-loader?sourceMap=true?sourceMap=true!sass-loader?outputStyle=expanded&sourceMap=true&sourceMapContents=true'
                        }

                    }
                },
                {
                    test: /\.vue$/,
                    exclude: /node_modules(?![\\/]vue-awesome[\\/])/,
                    include: [path.join(__dirname, 'node_modules/vue-awesome')],
                    loader: 'vue-loader',
                },
                {
                    test: /\.ts|\.js$/,
                    exclude: /node_modules(?![\\/]vue-awesome[\\/])/,
                    include: [path.join(__dirname, 'ClientApp')],
                    use: 'ts-loader'
                },
```
